services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: workspace
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/sport-spot
    volumes:
      - ./:/var/www/sport-spot
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: NgInX
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./:/var/www/sport-spot
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local